services:
  postgres:
    image: postgres:16-alpine
    container_name: desocial-db
    restart: unless-stopped
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: desocial
      POSTGRES_PASSWORD: desocial
      POSTGRES_DB: desocial
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
